# Generated by Django 6.0.1 on 2026-01-12 23:51

from django.db import migrations


def seed_actions(apps, schema_editor):
    Action = apps.get_model('core', 'Action')
    actions = [
        ('GI', 'Ground Intake', 0),
        ('TI', 'Top Intake', 0),
        ('SC', 'Score', 1),
        ('PS', 'Pass', 0),
        ('HF', 'Human Feed', 0),
        ('C1', 'Climb 1', 10),
        ('C2', 'Climb 2', 20),
        ('C3', 'Climb 3', 30),
        ('TEL', 'Start of Teleop', 0),
        ('AUT', 'Start of Auto', 0),
    ]
    for code, name, points in actions:
        Action.objects.create(code=code, name=name, points=points)


def remove_actions(apps, schema_editor):
    Action = apps.get_model('core', 'Action')
    Action.objects.filter(code__in=['GI', 'TI', 'SC', 'PS', 'HF', 'C1', 'C2', 'C3', 'TEL', 'AUT']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mark_count_mark_is_failure'),
    ]

    operations = [
        migrations.RunPython(seed_actions, remove_actions),
    ]
