# Generated by Django 6.0.1 on 2026-01-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_actions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='action',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
