# Generated by Django 6.0.1 on 2026-01-13 00:19

from django.db import migrations


def set_ordering(apps, schema_editor):
    Action = apps.get_model('core', 'Action')
    for action in Action.objects.all():
        action.ordering = action.id * 10
        action.save()


def reverse_ordering(apps, schema_editor):
    Action = apps.get_model('core', 'Action')
    Action.objects.all().update(ordering=0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_action_ordering'),
    ]

    operations = [
        migrations.RunPython(set_ordering, reverse_ordering),
    ]
