# Generated by Django 6.0.1 on 2026-01-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_set_action_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='delta_seconds',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
